[package]
name = "encodex"
version = "0.1.1"
edition = "2021"
authors = ["grqphical07"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", features = ["derive"]}